// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bivlyjhhfxwwuzhqxfny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpdmx5amhoZnh3d3V6aHF4Zm55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjkyNTMsImV4cCI6MjA1ODgwNTI1M30.880O5kp7ZI3XcBp_x9Pi5r-g9z5MqAc_mI0_s-75l70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);